apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bookinfo-application
spec:
  project: default
  source:
    repoURL: 'https://github.com/steppedaxis/devopshift-welcome.git'
    path: ./welcome/app/fe/bookinfo/manifests/manual
    targetRevision: argocd-workshop
    directory:
      recurse: true
      jsonnet: {}
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
