# If Values.argoApplication.install is true, install the ArgoCD Application.
{{- if .Values.argoApplication.install }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bookinfo-application
  namespace: argocd
spec:
  project: {{ .Values.argoApplication.project }}
  source:
    repoURL: '{{ .Values.argoApplication.repoURL }}'
    path: '{{ .Values.argoApplication.path }}'
    targetRevision: {{ .Values.argoApplication.targetRevision }}
  destination:
    server: {{ .Values.argoApplication.server }}
    namespace: {{ .Values.argoApplication.namespace }}
  syncPolicy:
    automated:
      prune: {{ .Values.argoApplication.prune }}
      selfHeal: {{ .Values.argoApplication.selfHeal }}
    syncOptions: 
      - CreateNamespace={{ .Values.argoApplication.CreateNamespace }}
    hooks:
      - type: PreSync
        kind: job
        manifest: |
          apiVersion: batch/v1
          kind: Job
          metadata:
            name: pre-sync-job
          spec:
            template:
              spec:
                containers:
                - name: example
                  image: busybox
                  command: ["/bin/sh", "-c"]
                  args: ["echo PreSync hook executed"]
                restartPolicy: Never
{{- end }}

