replicaCount: 1
replicaCount_details: 5
replicaCount_productPage: 2
replicaCount_ratings: 2
replicaCount_reviews: 2


image:
  tag: 1.19.1
  pullPolicy: IfNotPresent

details:
  image: docker.io/istio/examples-bookinfo-details-v1

ratings:
  image: docker.io/istio/examples-bookinfo-ratings-v1

reviews:
  image: docker.io/istio/examples-bookinfo-reviews-v1

productpage:
  image: docker.io/istio/examples-bookinfo-productpage-v1

service:
  type: LoadBalancer
  port: 80

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
